language: dart
sudo: false

dart:
- dev

dart_task:
- analyzer: --strong --fatal-warnings
- test: --platform мь
- test: --platform dartium
  install_dartium: true

branches:
  only:
  - gh-pages
  - /.*/

cache:
  directories:
    - $HOME/.pub-cache
