language: dart
sudo: false
dart:
- dev
dart_task:
- analyzer: --strong --fatal-warnings
- test: --platform vm
- test: --platform dartium
  install_dartium: true
script:
  - pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov

branches:
  only:
  - gh-pages
  - /.*/

cache:
  directories:
    - $HOME/.pub-cache
