language: dart
sudo: false
dart:
- dev
dart_task:
- analyzer: --strong --fatal-warnings
- test: --platform vm
- test: --platform dartium
  install_dartium: true
#- dartfmt

branches:
  only:
  - gh-pages
  - /.*/

cache:
  directories:
    - $HOME/.pub-cache
