language: dart
sudo: false
dart:
- dev
dart_task:
- test: --platform vm
- test: --platform dartium
install_dartium: true
- analyzer: --strong --fatal-warnings
#- dartfmt

branches:
  only:
  - gh-pages
  - /.*/

cache:
  directories:
    - $HOME/.pub-cache
